---
- hosts: all

  roles:
    - common
    - ssh
    - nfs
    - slurm

  tasks:
    - name: copy test scripts
      ansible.builtin.copy:
        src: test_scripts/
        dest: "{{ ansible_user_dir }}/slurm_test"
        mode: '0644'
      when: "'slurm_control_node' in group_names"

    - import_tasks: tasks/packages.yml

