---
- name: pacman -S slurm-llnl openpmix
  community.general.pacman:
    name:
      - slurm-llnl
      - openpmix
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: dnf install slurm
  ansible.builtin.dnf:
    name:
      - slurm
      - slurm-slurmctld
      - slurm-slurmd
    state: present
  become: true
  when: ansible_distribution == "Fedora" or ansible_distribution == "Rocky"

- name: apt install slurm-wlm
  ansible.builtin.apt:
    name: slurm-wlm
    state: present
  become: true
  when: ansible_distribution == "Debian"

