---
- name: copy munge.key
  ansible.builtin.copy:
    src: "{{ munge_key_file }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  become: true
  register: munge_key_file

- name: systemctl enable --now munge.service
  ansible.builtin.systemd: name=munge.service enabled=true state=started
  become: true

- name: set slurm_conf_dir (Archlinux)
  set_fact:
    slurm_conf_dir: /etc/slurm-llnl
  when: ansible_distribution == "Archlinux"

- name: set slurm_conf_dir (Fedora, Debian and Rocky)
  set_fact:
    slurm_conf_dir: /etc/slurm
  when: ansible_distribution == "Fedora" or ansible_distribution == "Debian" or ansible_distribution == "Rocky"

- name: copy slurm.conf to all nodes
  ansible.builtin.copy:
    src: "{{ slurm_config_file }}"
    dest: "{{ slurm_conf_dir }}/slurm.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
  register: slurm_conf

- name: copy cgroup.conf to all compute nodes
  ansible.builtin.copy:
    src: "{{ slurm_cgroup_config_file }}"
    dest: "{{ slurm_conf_dir }}/cgroup.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
  when: "'slurm_compute_nodes' in group_names"

- name: Create user slurm
  ansible.builtin.user:
    name: slurm
    uid: 64030
    create_home: false
    state: present
  become: true

- name: Create /var/spool/slurmctld
  ansible.builtin.file:
    path: /var/spool/slurmctld
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'
  become: true
  when: "'slurm_control_node' in group_names"

- name: Create /var/spool/slurmd
  ansible.builtin.file:
    path: /var/spool/slurmd
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'
  become: true
  when: "'slurm_compute_nodes' in group_names"

- name: Slurm run as user slurm (not root)
  ansible.builtin.shell: |
    systemctl stop slurmd.service
    systemctl stop slurmctld.service
    slurm-setuser -u slurm -g slurm -y
  become: true
  when:
    - ansible_distribution == "Fedora" or ansible_distribution == "Rocky"
    - slurm_conf.changed

- name: Create slurmd.service.d directory to modify nice value
  ansible.builtin.file:
    path: /etc/systemd/system/slurmd.service.d
    state: directory
  become: true
  when:
    - "'slurm_compute_nodes' in group_names"
    - slurmd_nice is defined

- name: Create drop in file to modify nice value
  ansible.builtin.copy:
    dest: /etc/systemd/system/slurmd.service.d/nice.conf
    content: |
      [Service]
      Nice={{ slurmd_nice }}
  become: true
  when:
    - "'slurm_compute_nodes' in group_names"
    - slurmd_nice is defined

- name: start and enable slurmctld.service on all control nodes
  ansible.builtin.systemd: name=slurmctld.service enabled=true state=started
  become: true
  when: "'slurm_control_node' in group_names"

- name: start and enable slurmd.service on all compute nodes
  ansible.builtin.systemd: name=slurmd.service enabled=true state=started
  become: true
  when: "'slurm_compute_nodes' in group_names"

